image: denoland/deno:latest

stages:
  - check
  - deploy

lint:
  stage: check
  script:
    - deno install --frozen
    - deno task lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

typecheck:
  stage: check
  script:
    - deno install --frozen
    - deno run -A npm:@inlang/paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide
    - ANTHROPIC_API_KEY=abc deno task check
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - deno install --frozen
    - deno task deploy
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  only:
    - main
